version: "3.0"
services: 
  scd-elastic:
    image: sergioadsf/scd-elastic:1.1
    container_name: scd-elastic
    ports: 
      - "8083:8083"
    depends_on: 
      - elasticsearch
    links: 
      - elasticsearch
    # networks:
    #   - scd-network

  elasticsearch:
    image: elasticsearch:6.6.1
    container_name: elasticsearch
    ports: 
      - "9200:9200"
      - "9300:9300"
    volumes: 
      - esdata1:/usr/share/elasticsearch/data
    # networks:
    #   - scd-network
    # environment:
    #   - XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=false
  
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    ports: 
      - "5601:5601"
    # networks: 
    #   - scd-network
    environment:
      # - SERVER_NAME=kibana.localhost
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      # - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_MONITORING_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
      - XPACK_SECURITY_ENABLED=false
    depends_on: 
      - elasticsearch
    links: 
      - elasticsearch

# networks: 
#   scd-network:
#     driver: bridge

volumes: 
  esdata1:
    driver: local
